export const rawskills = [
    "Angular",
    "jQuery",
    "Polymer",
    "React",
    "Vue.js",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Redux",
    "Zustand",
    "TypeScript",
    "Node.js",
    "Express.js",
    "NestJS",
    "GraphQL",
    "REST API",
    "MongoDB",
    "PostgreSQL",
    "Firebase",
    "Supabase",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Three.js",
    "WebRTC",
    "Socket.io",
    "D3.js",
    "Electron.js",
    "Docker",
    "Kubernetes",
    "Terraform",
    "AWS",
    "Azure",
    "Google Cloud",
    "Python",
    "Django",
    "Flask",
    "FastAPI",
    "Machine Learning",
    "AI/Deep Learning",
    "Blockchain",
    "Web3.js",
    "Solidity",
    "Cybersecurity",
    "CI/CD",
    "Jenkins",
    "GitHub Actions",
    "Redux Toolkit",
    "Vite"
];
